services:
  - type: web
    name: sistema-vendas-api
    env: node
    region: oregon
    plan: free
    buildCommand: cd backend && npm install
    startCommand: node backend/server.js
    envVars:
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        value: sua_chave_super_secreta
      - key: DATABASE_URL
        value: <"mongodb+srv://gomesjeremias:fIMwscYyfYUIXk66@cluster0.9teak4r.mongodb.net/Users?retryWrites=true&w=majority&appName=Cluster0">
